#pragma once

#include <iostream>
#include <fstream>
#include <vector>
#include <deque>
#include <set>
#include <memory>
#include <algorithm>
#include <chrono>
#include <map>
#include <unordered_map>
#include <string>
#include <type_traits>
#include <cassert>
#include <queue>
#include <functional>
#include "sol.hpp"
#include <glut.h>
#include "rapidjson\document.h"
#include "rapidjson\istreamwrapper.h"
